# Generated by Django 2.0 on 2018-01-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_auto_20180121_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='context_product',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='context_product',
            field=models.CharField(max_length=512),
        ),
    ]
